

name: CI/CD PyTorch CNN

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - run: |
          python -m pip install -U pip
          pip install flake8
          flake8 src tests

  tests:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - run: |
          pip install -r requirements.txt
          pytest -q

  docker_build:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t pytorch-cnn:${{ github.sha }} .

  smoke_test:
    runs-on: ubuntu-latest
    needs: docker_build
    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: docker build -t pytorch-cnn:${{ github.sha }} .

      # Exécute les tests dans le conteneur
      - name: Run container (pytest inside container)
        run: docker run --rm --name cnn pytorch-cnn:${{ github.sha }}

      - name: Show logs if failed
        if: failure()
        run: |
          docker ps -a || true
          docker logs cnn || true

