
name: CI/CD Python + Docker

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - run: |
          python -m pip install -U pip
          pip install flake8
          flake8 src tests

  tests:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - run: |
          pip install -r requirements.txt
          pip install pytest pytest-cov
          pytest -q --cov=src --cov-report=xml:coverage.xml

  build:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t app:${{ github.sha }} .

  smoke_test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Build image (cache local)
        run: docker build -t app:${{ github.sha }} .
      - name: Run container (smoke test)
        run: |
          docker run -d -p 8000:8000 --name app app:${{ github.sha }}
          sleep 4
          curl -f http://127.0.0.1:8000/health
      - name: Show logs if failed
        if: failure()
        run: docker logs app || true

  # (Option) Analyse qualité si tu as SONAR_TOKEN + sonar-project.properties
  sonar:
    runs-on: ubuntu-latest
    needs: smoke_test
    if: ${{ github.event_name == 'pull_request' || github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - run: |
          pip install -r requirements.txt
          pip install pytest pytest-cov
          pytest -q --cov=src --cov-report=xml:coverage.xml
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  push_image:
    runs-on: ubuntu-latest
    needs: [smoke_test]   # ou [sonar] si tu veux bloquer sur Sonar
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v4
      - name: Login Docker Hub
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "$PASSWORD" | docker login -u "$USERNAME" --password-stdin
      - name: Build & Push image
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          IMAGE=${USERNAME}/pyapp
          docker build -t $IMAGE:${{ github.sha }} -t $IMAGE:latest .
          docker push $IMAGE:${{ github.sha }}
          docker push $IMAGE:latest
